### ISSUE TITLE
Filtering a GeneratedProperty

### ISSUE THREAD

**Issue by russellhoff** [melistik/vaadin-grid-util#3]
I've realised that when I add a filter (e.g. filter.setTextFilter("tiempoMaxViajeFormateado", false, false);) to a column that has been added manually (e.g.: 

                 gpc.addGeneratedProperty("tiempoMaxViajeFormateado", new                   PropertyValueGenerator<String>() {

			private static final long serialVersionUID = -538133169393825256L;

			@Override
			public String getValue(Item item, Object itemId, Object propertyId) {
				BeanItem<PlanProvisional> bp = containerPlanesProvisionales.getItem(itemId);
				PlanProvisional pp = bp.getBean();
				return pp.getTiempoMaxViaje() + " min.";
			}

			@Override
			public Class<String> getType() {
				return String.class;
			}
			
		});

), I get an error in the console:

abr 27, 2015 12:54:27 PM com.vaadin.server.DefaultErrorHandler doDefault
GRAVE: 
com.vaadin.data.util.filter.UnsupportedFilterException: Filtercom.vaadin.data.util.filter.SimpleStringFilter@f129d4b5 is not supported
	at com.vaadin.data.util.PropertyValueGenerator.modifyFilter(PropertyValueGenerator.java:96)
	at com.vaadin.data.util.GeneratedPropertyContainer.addContainerFilter(GeneratedPropertyContainer.java:404)
	at org.vaadin.gridutil.cell.GridCellFilter.replaceFilter(GridCellFilter.java:201)
	at org.vaadin.gridutil.cell.GridCellFilter$1$1.textChange(GridCellFilter.java:247)
	at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:977)
	at com.vaadin.ui.AbstractTextField.firePendingTextChangeEvent(AbstractTextField.java:404)
	at com.vaadin.ui.AbstractTextField.changeVariables(AbstractTextField.java:213)
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:486)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:305)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:184)
	at com.vaadin.server.communication.PushHandler$3.run(PushHandler.java:176)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:255)
	at com.vaadin.server.communication.PushHandler.access$200(PushHandler.java:58)
	at com.vaadin.server.communication.PushHandler$1.onRequest(PushHandler.java:78)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:205)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:104)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:570)
	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:332)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:327)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:424)
	at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:206)
	at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:203)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:393)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:494)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:289)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:130)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:60)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:203)
	at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:194)
	at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:96)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

Why is that happening?

**Comment by melistik** [comment]
Hi, I've not tested to filter on a generated column. The reason for this problem is, that maybe a filter on generatedProperties is not possible in the same way like a normal ItemProperty. Could also be that it's generelly not possible. Give me some days to play with it.

Would be great if you could post your sample code that leads to this error...
Thanks in advance.

**Comment by russellhoff** [comment]
Hi @melistik. I already posted my sample code that lead to the issue. Tell me if you mean another code...

**Comment by melistik** [comment]
Asper my understanding the code of the GeneratedPropertyContainer filtering is only proceeded within the wrapped container when it implements Filterable (as for example the IndexContainer)... That's why you get an error. 

Propably you need to implement a custom Filter that will do the trick in DB :) or take a look at my [new example](https://github.com/melistik/vaadin-grid-util/commit/19b0d5ce4949f62253aa11086cbf68a5e03411f8) with custom filter and custom component...
